export const getMockProposalData = (id?: string) => {
  const proposalsData: Record<string, any> = {
    "QT-2025-0156": {
      id: id || "QT-2025-0156",
      documentNumber: "QT-2025-0156",
      proposalNumber: "QT-2025-0156",
      name: "Air Cargo Management System",
      customer: {
        company: "Bangkok Airways",
        companyTH: "สายการบินบางกอกแอร์เวย์",
        contact: "Mr. Supachai Wongchai",
        contactTH: "นายสุพชัย วงศ์ชัย",
        email: "supachai.w@bangkokair.com",
        phone: "+66 2 270 6699",
        address: "99 Mu 14 Vibhavadi Rangsit Road, Chom Phon, Chatuchak, Bangkok 10900",
        addressTH: "99 หมู่ 14 ถนนวิภาวดีรังสิต แขวงจอมพล เขตจตุจักร กรุงเทพมหานคร 10900",
        taxId: "0105536001449",
      },
      dealId: "DL-2025-156",
      status: "Approved",
      validUntil: "2025-02-10",
      issueDate: "2025-01-10",
      createdDate: "10 ม.ค. 2568",
      createdBy: {
        name: "Sarah Chen",
        initials: "SC",
        userId: "user1",
      },
      currency: "THB",
      includeVat: true,
      paymentTerm: "30",
      siteTH: "สนามบินสุวรรณภูมิ",
      siteEN: "Suvarnabhumi Airport",
      serviceTH: "ระบบบริหารจัดการสินค้าทางอากาศ",
      serviceEN: "Air Cargo Management System",
      descriptionTH: "ข้อเสนอนี้ครอบคลุมการพัฒนาและติดตั้งระบบบริหารจัดการสินค้าทางอากาศแบบครบวงจร รวมถึงระบบติดตาม ระบบจัดการคลังสินค้า และการรายงานแบบเรียลไทม์",
      descriptionEN: "This proposal covers the development and installation of a comprehensive air cargo management system, including tracking, warehouse management, and real-time reporting systems.",
      items: [
        {
          id: "1",
          itemName: "Air Cargo Management System",
          description: "ระบบบริหารจัดการสินค้าทางอากาศแบบครบวงจร",
          quantity: 1,
          unit: "Package",
          unitPrice: 2100000,
          discount: 0,
        },
      ],
      scopeOfWorksTH: [
        "การติดตั้งและปรับแต่งระบบ Air Cargo Management",
        "การฝึกอบรมพนักงานใช้งานระบบ",
        "การบำรุงรักษาระบบและให้การสนับสนุนทางเทคนิค",
        "การอัพเดทและปรับปรุงระบบอย่างต่อเนื่อง",
      ],
      scopeOfWorksEN: [
        "Installation and customization of Air Cargo Management System",
        "Staff training and system onboarding",
        "System maintenance and technical support",
        "Continuous system updates and improvements",
      ],
      remarksTH: [
        "ราคาที่เสนอเป็นสกุลเงินบาท",
        "ข้อเสนอนี้มีอายุ 31 วัน นับจากวันที่ออกเอกสาร",
        "เงื่อนไขการชำระเงิน: เครดิต 30 วัน",
        "การให้บริการจะเริ่มภายใน 15 วัน หลังลงนามสัญญา",
      ],
      remarksEN: [
        "All prices are quoted in Thai Baht (THB).",
        "This proposal is valid for 31 days from issue date.",
        "Payment term: Net 30 days.",
        "Service will commence within 15 days after contract signing.",
      ],
      termsAndConditionsTH: [
        "1. สัญญาการให้บริการ: ข้อเสนอนี้จะมีผลเป็นสัญญาที่มีผลผูกพันเมื่อทั้งสองฝ่ายยอมรับ",
        "2. ระยะเวลาการให้บริการ: ระยะเวลาการให้บริการจะเป็นไปตามที่ระบุในสัญญา โดยต่ออายุอัตโนมัติเว้นแต่จะมีการบอกเลิก",
        "3. เงื่อนไขการชำระเงิน: การชำระเงินจะต้องชำระภายใน 30 วัน นับจากวันที่ออกใบกำกับภาษี",
        "4. ความรับผิด: บริษัทจะรับผิดชอบต่อความเสียหายตามที่ระบุในสัญญาการให้บริการ",
        "5. เหตุสุดวิสัย: คู่สัญญาทั้งสองฝ่ายจะไม่ต้องรับผิดชอบต่อความล่าช้าอันเกิดจากเหตุการณ์ที่อยู่เหนือการควบคุม",
      ],
      termsAndConditionsEN: [
        "1. Service Agreement: This proposal becomes a binding agreement upon mutual acceptance by both parties.",
        "2. Service Period: The service period will be as specified in the contract, with automatic renewal unless terminated.",
        "3. Payment Terms: Payment must be made within 30 days from the invoice date.",
        "4. Liability: The company shall be liable for damages as specified in the service agreement.",
        "5. Force Majeure: Neither party shall be held responsible for delays caused by events beyond their control.",
      ],
      globalDiscount: 0,
      globalDiscountType: "percent" as "percent" | "amount",
    },
    "QT-2025-0142": {
      id: id || "QT-2025-0142",
      documentNumber: "QT-2025-0142",
      proposalNumber: "QT-2025-0142",
      name: "Freight Handling Solutions",
      customer: {
        company: "Thai Airways",
        companyTH: "สายการบินไทย",
        contact: "Mr. Thanawat Phongphan",
        contactTH: "นายธนวัฒน์ พงศ์พันธ์",
        email: "thanawat.p@thaiairways.com",
        phone: "+66 2 545 3000",
        address: "89 Vibhavadi Rangsit Road, Sanambin, Don Mueang, Bangkok 10210",
        addressTH: "89 ถนนวิภาวดีรังสิต แขวงสนามบิน เขตดอนเมือง กรุงเทพมหานคร 10210",
        taxId: "0107537000672",
      },
      dealId: "DL-2025-142",
      status: "Sent",
      validUntil: "2025-02-05",
      issueDate: "2025-01-05",
      createdDate: "5 ม.ค. 2568",
      createdBy: {
        name: "Michael Park",
        initials: "MP",
        userId: "user2",
      },
      currency: "THB",
      includeVat: true,
      paymentTerm: "45",
      siteTH: "สนามบินดอนเมือง",
      siteEN: "Don Mueang Airport",
      serviceTH: "บริการจัดการขนส่งสินค้า",
      serviceEN: "Freight Handling Solutions",
      descriptionTH: "ข้อเสนอนี้ครอบคลุมบริการจัดการขนส่งสินค้าแบบครบวงจร ประกอบด้วย การรับ-ส่งสินค้า การจัดเก็บ และการติดตามสินค้าแบบเรียลไทม์",
      descriptionEN: "This proposal covers comprehensive freight handling services including cargo receiving, storage, and real-time tracking solutions.",
      items: [
        {
          id: "1",
          itemName: "Freight Handling Solutions",
          description: "บริการจัดการขนส่งสินค้าแบบครบวงจร",
          quantity: 1,
          unit: "Package",
          unitPrice: 1800000,
          discount: 0,
        },
      ],
      scopeOfWorksTH: [
        "การรับและส่งมอบสินค้าที่สนามบิน",
        "การจัดเก็บสินค้าในคลังสินค้าที่ได้มาตรฐาน",
        "การติดตามสินค้าด้วยระบบ GPS",
        "บริการดูแลลูกค้าตลอด 24 ชั่วโมง",
      ],
      scopeOfWorksEN: [
        "Cargo receiving and delivery at airport",
        "Storage in certified warehouse facilities",
        "GPS tracking system",
        "24/7 customer support service",
      ],
      remarksTH: [
        "ราคาที่เสนอเป็นสกุลเงินบาท",
        "ข้อเสนอนี้มีอายุ 31 วัน นับจากวันที่ออกเอกสาร",
        "เงื่อนไขการชำระเงิน: เครดิต 45 วัน",
        "การให้บริการจะเริ่มภายใน 20 วัน หลังลงนามสัญญา",
      ],
      remarksEN: [
        "All prices are quoted in Thai Baht (THB).",
        "This proposal is valid for 31 days from issue date.",
        "Payment term: Net 45 days.",
        "Service will commence within 20 days after contract signing.",
      ],
      termsAndConditionsTH: [
        "1. สัญญาการให้บริการ: ข้อเสนอนี้จะมีผลเป็นสัญญาที่มีผลผูกพันเมื่อทั้งสองฝ่ายยอมรับ",
        "2. ระยะเวลาการให้บริการ: สัญญา 24 เดือน พร้อมต่ออายุอัตโนมัติ",
        "3. เงื่อนไขการชำระเงิน: การชำระเงินจะต้องชำระภายใน 45 วัน นับจากวันที่ออกใบกำกับภาษี",
        "4. ความรับผิด: บริษัทจะรับผิดชอบต่อความเสียหายตามที่ระบุในสัญญาการให้บริการ",
        "5. เหตุสุดวิสัย: คู่สัญญาทั้งสองฝ่ายจะไม่ต้องรับผิดชอบต่อความล่าช้าอันเกิดจากเหตุการณ์ที่อยู่เหนือการควบคุม",
      ],
      termsAndConditionsEN: [
        "1. Service Agreement: This proposal becomes a binding agreement upon mutual acceptance by both parties.",
        "2. Service Period: 24-month contract with automatic renewal option.",
        "3. Payment Terms: Payment must be made within 45 days from the invoice date.",
        "4. Liability: The company shall be liable for damages as specified in the service agreement.",
        "5. Force Majeure: Neither party shall be held responsible for delays caused by events beyond their control.",
      ],
      globalDiscount: 0,
      globalDiscountType: "percent" as "percent" | "amount",
    },
    "QT-2025-0178": {
      id: id || "QT-2025-0178",
      documentNumber: "QT-2025-0178",
      proposalNumber: "QT-2025-0178",
      name: "Energy Logistics Network",
      customer: {
        company: "PTT Energy",
        companyTH: "พีทีที เอนเนอร์ยี่",
        contact: "Ms. Apinya Suvannakul",
        contactTH: "นางสาวอภิญญา สุวรรณกุล",
        email: "apinya.s@pttenergy.com",
        phone: "+66 2 537 2000",
        address: "555 Vibhavadi Rangsit Road, Chatuchak, Bangkok 10900",
        addressTH: "555 ถนนวิภาวดีรังสิต แขวงจตุจักร เขตจตุจักร กรุงเทพมหานคร 10900",
        taxId: "0107536000562",
      },
      dealId: "DL-2025-178",
      status: "Approved",
      validUntil: "2025-02-15",
      issueDate: "2025-01-15",
      createdDate: "15 ม.ค. 2568",
      createdBy: {
        name: "Lisa Thompson",
        initials: "LT",
        userId: "user3",
      },
      currency: "THB",
      includeVat: true,
      paymentTerm: "60",
      siteTH: "โรงกลั่นน้ำมันระยอง",
      siteEN: "Rayong Refinery",
      serviceTH: "โซลูชั่นการขนส่งพลังงาน",
      serviceEN: "Energy Logistics Network",
      descriptionTH: "ข้อเสนอนี้ครอบคลุมการพัฒนาเครือข่ายโลจิสติกส์สำหรับการขนส่งพลังงาน รวมถึงการจัดการความปลอดภัย การติดตาม และการรายงานแบบครบวงจร",
      descriptionEN: "This proposal covers the development of an energy logistics network, including safety management, tracking, and comprehensive reporting solutions.",
      items: [
        {
          id: "1",
          itemName: "Energy Logistics Network",
          description: "โซลูชั่นการขนส่งพลังงานแบบครบวงจร",
          quantity: 1,
          unit: "Package",
          unitPrice: 3500000,
          discount: 0,
        },
      ],
      scopeOfWorksTH: [
        "การพัฒนาเครือข่ายขนส่งพลังงานที่ปลอดภัย",
        "ระบบติดตามและรายงานแบบเรียลไทม์",
        "การจัดการความปลอดภัยตามมาตรฐาน ISO 45001",
        "การประกันภัยครอบคลุมเต็มมูลค่า",
      ],
      scopeOfWorksEN: [
        "Development of secure energy transportation network",
        "Real-time tracking and reporting system",
        "Safety management according to ISO 45001 standards",
        "Full value insurance coverage",
      ],
      remarksTH: [
        "ราคาที่เสนอเป็นสกุลเงินบาท",
        "ข้อเสนอนี้มีอายุ 31 วัน นับจากวันที่ออกเอกสาร",
        "เงื่อนไขการชำระเงิน: เครดิต 60 วัน",
        "การให้บริการจะเริ่มภายใน 30 วัน หลังลงนามสัญญา",
      ],
      remarksEN: [
        "All prices are quoted in Thai Baht (THB).",
        "This proposal is valid for 31 days from issue date.",
        "Payment term: Net 60 days.",
        "Service will commence within 30 days after contract signing.",
      ],
      termsAndConditionsTH: [
        "1. สัญญาการให้บริการ: ข้อเสนอนี้จะมีผลเป็นสัญญาที่มีผลผูกพันเมื่อทั้งสองฝ่ายยอมรับ",
        "2. ระยะเวลาการให้บริการ: สัญญา 36 เดือน พร้อมต่ออายุอัตโนมัติ",
        "3. เงื่อนไขการชำระเงิน: การชำระเงินจะต้องชำระภายใน 60 วัน นับจากวันที่ออกใบกำกับภาษี",
        "4. ความรับผิด: บริษัทจะรับผิดชอบต่อความเสียหายตามที่ระบุในสัญญาการให้บริการ พร้อมประกันภัยครอบคลุม",
        "5. เหตุสุดวิสัย: คู่สัญญาทั้งสองฝ่ายจะไม่ต้องรับผิดชอบต่อความล่าช้าอันเกิดจากเหตุการณ์ที่อยู่เหนือการควบคุม",
      ],
      termsAndConditionsEN: [
        "1. Service Agreement: This proposal becomes a binding agreement upon mutual acceptance by both parties.",
        "2. Service Period: 36-month contract with automatic renewal option.",
        "3. Payment Terms: Payment must be made within 60 days from the invoice date.",
        "4. Liability: The company shall be liable for damages as specified in the service agreement, with full insurance coverage.",
        "5. Force Majeure: Neither party shall be held responsible for delays caused by events beyond their control.",
      ],
      globalDiscount: 0,
      globalDiscountType: "percent" as "percent" | "amount",
    },
    "QT-2025-0089": {
      id: id || "QT-2025-0089",
      documentNumber: "QT-2025-0089",
      proposalNumber: "QT-2025-0089",
      name: "F&B Supply Chain Solution",
      customer: {
        company: "Central Food Hall",
        companyTH: "เซ็นทรัล ฟู้ด ฮอลล์",
        contact: "Ms. Narisa Wongsuwan",
        contactTH: "นางสาวนริศา วงศ์สุวรรณ",
        email: "narisa.w@centralfood.com",
        phone: "+66 2 021 9999",
        address: "4, 4/1-4/2 Rajdamri Road, Lumpini, Pathumwan, Bangkok 10330",
        addressTH: "4, 4/1-4/2 ถนนราชดำริ แขวงลุมพินี เขตปทุมวัน กรุงเทพมหานคร 10330",
        taxId: "0107536000089",
      },
      dealId: "DL-2025-089",
      status: "Draft",
      validUntil: "2025-02-03",
      issueDate: "2025-01-03",
      createdDate: "3 ม.ค. 2568",
      createdBy: {
        name: "Emily Rodriguez",
        initials: "ER",
        userId: "user4",
      },
      currency: "THB",
      includeVat: true,
      paymentTerm: "30",
      siteTH: "ศูนย์กระจายสินค้าเซ็นทรัล",
      siteEN: "Central Distribution Center",
      serviceTH: "โซลูชั่นซัพพลายเชนอาหารและเครื่องดื่ม",
      serviceEN: "F&B Supply Chain Solution",
      descriptionTH: "ข้อเสนอนี้ครอบคลุมระบบจัดการซัพพลายเชนอาหารและเครื่องดื่มแบบครบวงจร รวมถึงคลังสินค้าควบคุมอุณหภูมิ ระบบติดตาม และการจัดส่งรวดเร็ว",
      descriptionEN: "This proposal covers comprehensive F&B supply chain management including temperature-controlled warehousing, tracking system, and fast delivery services.",
      items: [
        {
          id: "1",
          itemName: "F&B Supply Chain Solution",
          description: "ระบบจัดการซัพพลายเชนอาหารและเครื่องดื่มแบบครบวงจร",
          quantity: 1,
          unit: "Package",
          unitPrice: 450000,
          discount: 0,
        },
      ],
      scopeOfWorksTH: [
        "คลังสินค้าควบคุมอุณหภูมิตามมาตรฐาน HACCP",
        "ระบบติดตามสินค้าแบบเรียลไทม์",
        "บริการจัดส่งรวดเร็วภายใน 24 ชั่วโมง",
        "การจัดการคุณภาพและความปลอดภัยของอาหาร",
      ],
      scopeOfWorksEN: [
        "HACCP-certified temperature-controlled warehouse",
        "Real-time product tracking system",
        "Express delivery within 24 hours",
        "Food quality and safety management",
      ],
      remarksTH: [
        "ราคาที่เสนอเป็นสกุลเงินบาท",
        "ข้อเสนอนี้มีอายุ 31 วัน นับจากวันที่ออกเอกสาร",
        "เงื่อนไขการชำระเงิน: เครดิต 30 วัน",
        "การให้บริการจะเริ่มภายใน 10 วัน หลังลงนามสัญญา",
      ],
      remarksEN: [
        "All prices are quoted in Thai Baht (THB).",
        "This proposal is valid for 31 days from issue date.",
        "Payment term: Net 30 days.",
        "Service will commence within 10 days after contract signing.",
      ],
      termsAndConditionsTH: [
        "1. สัญญาการให้บริการ: ข้อเสนอนี้จะมีผลเป็นสัญญาที่มีผลผูกพันเมื่อทั้งสองฝ่ายยอมรับ",
        "2. ระยะเวลาการให้บริการ: สัญญา 12 เดือน พร้อมต่ออายุอัตโนมัติ",
        "3. เงื่อนไขการชำระเงิน: การชำระเงินจะต้องชำระภายใน 30 วัน นับจากวันที่ออกใบกำกับภาษี",
        "4. ความรับผิด: บริษัทจะรับผิดชอบต่อความเสียหายตามที่ระบุในสัญญาการให้บริการ",
        "5. เหตุสุดวิสัย: คู่สัญญาทั้งสองฝ่ายจะไม่ต้องรับผิดชอบต่อความล่าช้าอันเกิดจากเหตุการณ์ที่อยู่เหนือการควบคุม",
      ],
      termsAndConditionsEN: [
        "1. Service Agreement: This proposal becomes a binding agreement upon mutual acceptance by both parties.",
        "2. Service Period: 12-month contract with automatic renewal option.",
        "3. Payment Terms: Payment must be made within 30 days from the invoice date.",
        "4. Liability: The company shall be liable for damages as specified in the service agreement.",
        "5. Force Majeure: Neither party shall be held responsible for delays caused by events beyond their control.",
      ],
      globalDiscount: 0,
      globalDiscountType: "percent" as "percent" | "amount",
    },
  };

  // Return specific proposal data or default
  return proposalsData[id || ""] || {
    id: id || "PRP-2024-001",
    documentNumber: "PRP2024123456",
    proposalNumber: "PRP-2024-001",
    name: "Logistics Services Proposal",
    customer: {
      company: "Technology Innovation Co., Ltd.",
      companyTH: "บริษัท เทคโนโลยี อินโนเวชั่น จำกัด",
      contact: "Ms. Wipawee Somwang",
      contactTH: "คุณวิภาวี สมหวัง",
      email: "wipawee.s@techinnovation.com",
      phone: "+66 2 345 6789",
      address: "123 Sukhumvit Road, Khlong Toei, Bangkok 10110, Thailand",
      addressTH: "123 ถนนสุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพมหานคร 10110",
      taxId: "0105559876543",
    },
    dealId: "DL-2024-189",
    status: "Draft",
    validUntil: "2024-03-15",
    issueDate: "2024-02-15",
    createdDate: "15 ก.พ. 2567",
    createdBy: {
      name: "Sarah Chen",
      initials: "SC",
      userId: "user1",
    },
    currency: "THB",
    includeVat: true,
    paymentTerm: "30",
    siteTH: "โรงงานบางปู สมุทรปราการ",
    siteEN: "Bangpu Factory, Samutprakarn",
    serviceTH: "บริการขนส่งสินค้าทางบก",
    serviceEN: "Land Transportation Service",
    descriptionTH: "ข้อเสนอนี้ครอบคลุมบริการโลจิสติกส์แบบครบวงจร ประกอบด้วย คลังสินค้า การขนส่ง และการบริหารจัดการห่วงโซ่อุปทาน โดยมีรายละเอียดตามที่ระบุในขอบเขตการดำเนินงานด้านล่าง",
    descriptionEN: "This proposal covers comprehensive logistics services including warehousing, transportation, and supply chain management, with details as specified in the scope of works below.",
    items: [
      {
        id: "1",
        itemName: "บริการขนส่งทางบก (Land Transportation)",
        description: "ขนส่งสินค้าทางบกภายในประเทศ - ปริมาณ 50 ตัน/เดือน",
        quantity: 12,
        unit: "เดือน",
        unitPrice: 150000,
        discount: 0,
      },
      {
        id: "2",
        itemName: "บริการคลังสินค้า (Warehousing)",
        description: "เช่าพื้นที่คลังสินค้า 1,000 ตารางเมตร รวมบริหารจัดการ",
        quantity: 12,
        unit: "เดือน",
        unitPrice: 80000,
        discount: 0,
      },
      {
        id: "3",
        itemName: "ระบบติดตามสินค้า (Tracking System)",
        description: "ระบบ GPS และซอฟต์แวร์บริหารจัดการ พร้อม Real-time Dashboard",
        quantity: 1,
        unit: "ชุด",
        unitPrice: 50000,
        discount: 10,
      },
    ],
    scopeOfWorksTH: [
      "การบริหารจัดการคลังสินค้าและควบคุมสต็อก",
      "การวางแผนและดำเนินการขนส่ง",
      "ระบบติดตามและรายงานแบบเรียลไทม์",
      "บริการดูแลลูกค้าตลอด 24 ชั่วโมง",
    ],
    scopeOfWorksEN: [
      "Warehouse management and inventory control",
      "Transportation planning and execution",
      "Real-time tracking and reporting",
      "Customer service support 24/7",
    ],
    remarksTH: [
      "ราคาที่เสนอเป็นสกุลเงินบาท",
      "ข้อเสนอนี้มีอายุ 30 วัน นับจากวันที่ออกเอกสาร",
      "เงื่อนไขการชำระเงิน: เครดิต 30 วัน",
      "การให้บริการจะเริ่มภายใน 15 วัน หลังลงนามสัญญา",
    ],
    remarksEN: [
      "All prices are quoted in Thai Baht (THB).",
      "This proposal is valid for 30 days from issue date.",
      "Payment term: Net 30 days.",
      "Service will commence within 15 days after contract signing.",
    ],
    termsAndConditionsTH: [
      "1. สัญญาการให้บริการ: ข้อเสนอนี้จะมีผลเป็นสัญญาที่มีผลผูกพันเมื่อทั้งสองฝ่ายยอมรับ",
      "2. ระยะเวลาการให้บริการ: ระยะเวลาการให้บริการจะเป็นไปตามที่ระบุในสัญญา โดยต่ออายุอัตโนมัติเว้นแต่จะมีการบอกเลิก",
      "3. เงื่อนไขการชำระเงิน: การชำระเงินจะต้องชำระภายใน 30 วัน นับจากวันที่ออกใบกำกับภาษี",
      "4. ความรับผิด: บริษัทจะรับผิดชอบต่อความเสียหายตามที่ระบุในสัญญาการให้บริการ",
      "5. เหตุสุดวิสัย: คู่สัญญาทั้งสองฝ่ายจะไม่ต้องรับผิดชอบต่อความล่าช้าอันเกิดจากเหตุการณ์ที่อยู่เหนือการควบคุม",
    ],
    termsAndConditionsEN: [
      "1. Service Agreement: This proposal shall become a binding agreement upon acceptance by both parties.",
      "2. Service Period: The service period shall be as specified in the contract, with automatic renewal unless terminated.",
      "3. Payment Terms: Payment shall be made within 30 days from invoice date.",
      "4. Liability: The Company shall be liable for damages as specified in the service agreement.",
      "5. Force Majeure: Neither party shall be liable for delays due to circumstances beyond reasonable control.",
    ],
    globalDiscount: 0,
    globalDiscountType: "percent" as "percent" | "amount",
  };
};

// Function to convert proposal data for preview screen
export const getMockProposalPreviewData = (id?: string) => {
  const proposalData = getMockProposalData(id);
  
  return {
    ...proposalData,
    company: {
      name: "ONELINK LOGISTICS CO., LTD.",
      address: "123 Sukhumvit Road, Khlong Toei, Bangkok 10110, Thailand",
      phone: "+66 2 345 6789",
      email: "contact@onelink-logistics.com",
      taxId: "0105559012345",
      website: "www.onelink-logistics.com",
    },
    benefits: [
      "ประหยัดค่าใช้จ่ายในการขนส่งได้ถึง 30%",
      "ระบบติดตามสินค้าแบบเรียลไทม์ พร้อมรายงานครบถ้วน",
      "ทีมงานมืออาชีพพร้อมให้บริการตลอด 24 ชั่วโมง",
      "มาตรฐานคุณภาพระดับสากล ISO 9001 และ ISO 14001",
      "เครือข่ายกว้างครอบคลุมทั่วประเทศและต่างประเทศ",
    ],
    remarks: proposalData.remarksTH?.join("\\n") || "ราคาที่เสนอเป็นสกุลเงินบาท\\nข้อเสนอนี้มีอายุ 31 วัน นับจากวันที่ออกเอกสาร\\nเงื่อนไขการชำระเงิน: เครดิต 30 วัน\\nการให้บริการจะเริ่มภายใน 15 วัน หลังลงนามสัญญา",
    validity: 31,
    signatureProviderName: "Ms. Sarah Chen",
    signatureProviderPosition: "Sales Manager",
    signatureProviderDate: proposalData.issueDate,
    signatureProviderImage: "",
    signatureReceivers: [
      {
        id: "receiver1",
        name: proposalData.customer.contact || "",
        position: "Authorized Representative",
        date: "",
        image: "",
      },
    ],
  };
};

// Function to convert proposal data for editor-v2 screen
export const getMockProposalEditorData = (id?: string) => {
  const proposalData = getMockProposalData(id);
  
  // Safety check
  if (!proposalData || !proposalData.items || !Array.isArray(proposalData.items)) {
    console.error("Invalid proposalData or items:", proposalData);
    return {
      id: id || "PRP-2024-001",
      companyLogo: "onelink-logo.png",
      companyNameTH: "บริษัท วันลิงค์ โลจิสติกส์ จำกัด",
      companyNameEN: "ONELINK LOGISTICS CO., LTD.",
      companyAddress: "999 อาคารออฟฟิศพาร์ค ชั้น 15 ถนนพระราม 4 แขวงสีลม เขตบางรัก กรุงเทพมหานคร 10500 โทร: 02-234-5678",
      documentTitleTH: "ข้อเสนอโครงการ",
      documentTitleEN: "Business Proposal",
      siteTH: "โรงงานบางปู สมุทรปราการ",
      siteEN: "Bangpu Factory, Samutprakarn",
      serviceTH: "บริการขนส่งสินค้าทางบก",
      serviceEN: "Land Transportation Service",
      customerCompanyTH: "บริษัท เทคโนโลยี อินโนเวชั่น จำกัด",
      customerCompanyEN: "Technology Innovation Co., Ltd.",
      customerContactName: "คุณวิภาวี สมหวัง",
      customerPosition: "ผู้ติดต่อ",
      customerAddress: "123 ถนนสุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพมหานคร 10110",
      customerPhone: "+66 2 345 6789",
      customerEmail: "wipawee.s@techinnovation.com",
      customerTaxId: "0105559876543",
      proposalNumber: "PRP-2024-001",
      issueDate: new Date().toISOString().split('T')[0],
      validUntil: new Date(Date.now() + 31*24*60*60*1000).toISOString().split('T')[0],
      issueStatus: "Draft",
      issuedBy: "Sarah Chen",
      issuedByCompany: "บริษัท วันลิงค์ โลจิสติกส์ จำกัด",
      issuedEmail: "sarah.chen@onelink-logistics.com",
      customerNameForIntro: "คุณวิภาวี สมหวัง",
      introParagraphTH: "เรามีความยินดีที่จะนำเสนอข้อเสนอบริการโลจิสติกส์นี้ บริษัทของเรามีประสบการณ์กว่า 20 ปีในการให้บริการโซลูชั่นห่วงโซ่อุปทานแบบครบวงจร เรามุ่งมั่นในการให้บริการที่มีคุณภาพสูงสุดแก่ลูกค้าทุกท่าน",
      introParagraphEN: "We are pleased to present this proposal for logistics services. Our company has over 20 years of experience in providing comprehensive supply chain solutions. We are committed to delivering the highest quality service to all our customers.",
      descriptionTH: "ข้อเสนอนี้ครอบคลุมบริการโลจิสติกส์แบบครบวงจร",
      descriptionEN: "This proposal covers comprehensive logistics services.",
      scopeOfWorksTH: [
        "การบริหารจัดการคลังสินค้าและควบคุมสต็อก",
        "การวางแผนและดำเนินการขนส่ง",
        "ระบบติดตามและรายงานแบบเรียลไทม์",
        "บริการดูแลลูกค้าตลอด 24 ชั่วโมง"
      ],
      scopeOfWorksEN: [
        "Warehouse management and inventory control",
        "Transportation planning and execution",
        "Real-time tracking and reporting",
        "Customer service support 24/7"
      ],
      items: [
        {
          id: "1",
          no: "1",
          descriptionTH: "บริการขนส่งทางบก",
          descriptionEN: "Land Transportation Service",
          unit: "เดือน",
          quantity: 12,
          unitPrice: 150000,
          discount: 0,
        },
      ],
      remarksTH: [
        "ราคาที่เสนอเป็นสกุลเงินบาท",
        "ข้อเสนอนี้มีอายุ 31 วัน นับจากวันที่ออกเอกสาร",
        "เงื่อนไขการชำระเงิน: เครดิต 30 วัน",
      ],
      remarksEN: [
        "All prices are quoted in Thai Baht (THB).",
        "This proposal is valid for 31 days from issue date.",
        "Payment term: Net 30 days.",
      ],
      termsAndConditionsTH: [
        "1. สัญญาการให้บริการ: ข้อเสนอนี้จะมีผลเป็นสัญญาที่มีผลผูกพันเมื่อทั้งสองฝ่ายยอมรับ",
        "2. ระยะเวลาการให้บริการ: ระยะเวลาการให้บริการจะเป็นไปตามที่ระบุในสัญญา",
      ],
      termsAndConditionsEN: [
        "1. Service Agreement: This proposal becomes a binding agreement upon mutual acceptance.",
        "2. Service Period: The service period will be as specified in the contract.",
      ],
      globalDiscount: 0,
      globalDiscountType: "percent" as "percent" | "amount",
      includeVat: true,
      paymentTerm: "30",
      currency: "THB",
    };
  }
  
  return {
    id: proposalData.id,
    
    // Company info
    companyLogo: "onelink-logo.png",
    companyNameTH: "บริษัท วันลิงค์ โลจิสติกส์ จำกัด",
    companyNameEN: "ONELINK LOGISTICS CO., LTD.",
    companyAddress: "999 อาคารออฟฟิศพาร์ค ชั้น 15 ถนนพระราม 4 แขวงสีลม เขตบางรัก กรุงเทพมหานคร 10500 โทร: 02-234-5678",
    documentTitleTH: "ข้อเสนอโครงการ",
    documentTitleEN: "Business Proposal",
    
    // Site/Project info
    siteTH: proposalData.siteTH || "โรงงานบางปู สมุทรปราการ",
    siteEN: proposalData.siteEN || "Bangpu Factory, Samutprakarn",
    serviceTH: proposalData.serviceTH || "บริการขนส่งสินค้าทางบก",
    serviceEN: proposalData.serviceEN || "Land Transportation Service",
    
    // Customer info
    customerCompanyTH: proposalData.customer?.companyTH || proposalData.customer?.company || "",
    customerCompanyEN: proposalData.customer?.company || "",
    customerContactName: proposalData.customer?.contact || "",
    customerPosition: "ผู้ติดต่อ",
    customerAddress: proposalData.customer?.addressTH || proposalData.customer?.address || "",
    customerPhone: proposalData.customer?.phone || "",
    customerEmail: proposalData.customer?.email || "",
    customerTaxId: proposalData.customer?.taxId || "",
    
    // Document info
    proposalNumber: proposalData.proposalNumber || proposalData.documentNumber,
    issueDate: proposalData.issueDate,
    validUntil: proposalData.validUntil,
    issueStatus: proposalData.status,
    
    // User info
    issuedBy: proposalData.createdBy?.name || "Sarah Chen",
    issuedByCompany: "บริษัท วันลิงค์ โลจิสติกส์ จำกัด",
    issuedEmail: "sarah.chen@onelink-logistics.com",
    
    // Description
    customerNameForIntro: proposalData.customer?.contact || "",
    introParagraphTH: "เรามีความยินดีที่จะนำเสนอข้อเสนอบริการโลจิสติกส์นี้ บริษัทของเรามีประสบการณ์กว่า 20 ปีในการให้บริการโซลูชั่นห่วงโซ่อุปทานแบบครบวงจร เรามุ่งมั่นในการให้บริการที่มีคุณภาพสูงสุดแก่ลูกค้าทุกท่าน",
    introParagraphEN: "We are pleased to present this proposal for logistics services. Our company has over 20 years of experience in providing comprehensive supply chain solutions. We are committed to delivering the highest quality service to all our customers.",
    
    descriptionTH: proposalData.descriptionTH || "",
    descriptionEN: proposalData.descriptionEN || "",
    
    scopeOfWorksTH: proposalData.scopeOfWorksTH || [],
    scopeOfWorksEN: proposalData.scopeOfWorksEN || [],
    
    // Items - convert format
    items: proposalData.items.map((item: any, index: number) => ({
      id: item.id || String(index + 1),
      no: String(index + 1),
      descriptionTH: item.itemName || item.description || "",
      descriptionEN: item.itemName || item.description || "",
      unit: item.unit || "ชุด",
      quantity: item.quantity || 1,
      unitPrice: item.unitPrice || 0,
      discount: item.discount || 0,
    })),
    
    remarksTH: proposalData.remarksTH || [],
    remarksEN: proposalData.remarksEN || [],
    termsAndConditionsTH: proposalData.termsAndConditionsTH || [],
    termsAndConditionsEN: proposalData.termsAndConditionsEN || [],
    
    // Pricing
    globalDiscount: proposalData.globalDiscount || 0,
    globalDiscountType: proposalData.globalDiscountType || "percent",
    includeVat: proposalData.includeVat !== false,
    paymentTerm: proposalData.paymentTerm || "30",
    currency: proposalData.currency || "THB",
  };
};